---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-redis-cm
  labels:
    app: {{.Release.Name}}
data:
  redis.conf: |
    {{- with .Values.config }}
    {{- range $key, $value := . }}
    {{ $key }} {{ $value }}
    {{- end }}
    {{- end }}
